### ISSUE TITLE
doesn't compile with nginx-openresty1.5.12.1(nginx1.5.12)?

### ISSUE THREAD

**Issue by useyourfeelings** [laocai/tcp-nginx-module#1]
i got tons of errors like:

ngx_tcp_core_module.c:974:24: error: 'ngx_tcp_core_main_conf_t' has no member named 'error_log'
         ls->logp = cmcf->error_log;

ngx_tcp_core_module.c:971:13: error: 'ngx_tcp_core_main_conf_t' has no member named 'error_log'
     if (cmcf->error_log == NULL) {

ngx_tcp_core_module.c:744:19: error: 'ngx_tcp_listen_t' has no member named 'so_keepalive'
                 ls->so_keepalive = 1;

**Comment by laocai** [comment]
Yes, It will compile error in nginx version highter than 1.4. I will solve  the problem in the future.
